### ISSUE TITLE
Installation error and solution

### ISSUE THREAD

**Issue by lhy0807** [elevenjiang1/ObjectInHand-Dataset#1]
Thanks for the amazing work. While installing the package using the instruction, I faced some compilation error. I tried the following solution and solved the issue.

1. Remove the provided sr_core
2. Git clone the official sr_core repo https://github.com/shadow-robot/sr_core
3. Git clone the official common_resources https://github.com/shadow-robot/common_resources
Maybe you could add git submodules to these official repos in the src folder?

**Comment by elevenjiang1** [comment]
Thanks for your advice~ 
Could you give more detailed information about the compilation error? Like the Ubuntu version or other compile error info? So that I can decide whether to change the module or add a new branch, since I can use the code in my computer (Ubuntu 18.04). 
Our docker image can be found at: https://hub.docker.com/r/elevenjiang/objectinhand/tags

**Comment by lhy0807** [comment]
Thanks for the reply! I think that might be the issue.. I'm using Ubuntu 20.04 + ROS noetic
